export const popularCategoryArr = {
  business: [
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'GIL <br> PETERSIL',
      pos: 'Mastering Networking',
    },
    {
      imgLink: './img/popular/persons/img2.jpg',
      label: 'New',
      rate: '4.5',
      rateIcon: './img/stories/star-half.svg',
      name: 'GREG <br> REID',
      pos: 'Pathways To Greatness',
    },
    {
      imgLink: './img/popular/persons/img3.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'GREG <br> REID',
      pos: 'Mastering AirBnb Business',
    },
    {
      imgLink: './img/popular/persons/img4.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Omar Al <br> Busaidy',
      pos: ' Mastering Business <br> Development',
    },
    {
      imgLink: './img/popular/persons/img5.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Bashar J. <br /> Katou',
      pos: 'Mastering Amazon FBA',
    },
    // {
    //   imgLink: './img/popular/persons/img6.jpg',
    //   label: 'New',
    //   rate: '5.0',
    //   rateIcon: './img/stories/star-fill.svg',
    //   name: 'Bashar J. <br> Katou',
    //   pos: 'Mastering Amazon FBA',
    // },
  ],
  finance: [
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> lorem',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
  ],
  marketing: [
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
  ],
  philosophy: [
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
  ],
  nft: [
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
  ],
  cryptocurrency: [
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
  ],
  sales: [
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
  ],
  management: [
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
    {
      imgLink: './img/popular/persons/img.jpg',
      label: 'New',
      rate: '5.0',
      rateIcon: './img/stories/star-fill.svg',
      name: 'Melody <br> Hobson',
      pos: 'Mastering <br> The Markets',
    },
  ],
};
